-- create table
-- !! Do not ever change "create table" - add separate "alter table" statements bellow

create table app_parameters (
    id              number generated by default on null as identity
                    constraint app_parameters_id_pk primary key,
    parameter       varchar2(100 char)
                    constraint app_parameters_parameter_unq unique not null,
    parameter_type  varchar2(10 char) not null constraint app_parameters_parameter_type_ck
                    check (parameter_type in ('STRING','BOOLEAN','NUMBER','DATE','CLOB','BLOB')),
    display_name    varchar2(100 char) not null,
    description     varchar2(2000 char) not null,
    lov             varchar2(2000 char),
    value_string    varchar2(2000 char),
    value_number    number,
    value_date      date,
    value_clob      clob,
    value_blob      blob,
    row_version     integer not null,
    created         date not null,
    created_by      varchar2(255 char) not null,
    updated         date not null,
    updated_by      varchar2(255 char) not null
);
-- alter table


-- triggers
create or replace trigger app_parameters_biu
    before insert or update
    on app_parameters
    for each row
begin
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := NVL(:old.row_version, 0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end app_parameters_biu;
/


-- Generated by Quick SQL undefined 1/3/2024, 2:18:54 PM

/*
app_parameters
  parameter vc100 /nn /unique
  parameter_type vc10 /nn /check STRING,BOOLEAN,NUMBER,DATE,CLOB,BLOB
  display_name vc100 /nn 
  description vc2000 /nn
  lov vc2000
  value_string vc2000
  value_number number
  value_date date
  value_clob clob
  value_blob blob

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","db":"19c","rowversion":"Y"}

*/