-- create table
-- !! Do not ever change "create table" - add separate "alter table" statements bellow

create table app_parameter_tags (
    id                  number generated by default on null as identity
                        constraint app_parameter_tags_id_pk primary key,
    app_parameter_id    number
                        constraint app_parameter_tags_app_parameter_id_fk
                        references app_parameters,
    tag                 varchar2(100 char) not null,
    value               varchar2(2000 char),
    row_version         integer not null,
    created             date not null,
    created_by          varchar2(255 char) not null,
    updated             date not null,
    updated_by          varchar2(255 char) not null
);


-- alter table
alter table app_parameter_tags add constraint app_parameter_tags_unq unique (app_parameter_id, tag);

-- triggers
create or replace trigger app_parameter_tags_biu
    before insert or update
    on app_parameter_tags
    for each row
begin
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := NVL(:old.row_version, 0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end app_parameter_tags_biu;
/
